import React, { createContext, useContext, useState } from 'react';

export const LanguageContext = createContext();

// ─── Translations dictionary ──────────────────────────────────────────────────
const translations = {
    ru: {
        // Header / Nav
        nav_home:       'Главная',
        nav_nutrition:  'Питание',
        nav_analytics:  'Аналитика',
        nav_profile:    'Профиль',
        nav_login:      'Войти',
        nav_register:   'Регистрация',
        nav_logout:     'Выйти',
        toggle_theme:   'Переключить тему',
        toggle_lang:    'EN',

        // Login
        login_title:        'Добро пожаловать',
        login_subtitle:     'Войдите в аккаунт, чтобы продолжить',
        login_email:        'Email',
        login_password:     'Пароль',
        login_show_pass:    'Показать пароль',
        login_hide_pass:    'Скрыть пароль',
        login_forgot:       'Забыли пароль?',
        login_submit:       'Войти',
        login_loading:      'Вход...',
        login_no_account:   'Нет аккаунта?',
        login_signup:       'Зарегистрироваться',
        login_slogan:       'Твой персональный помощник в достижении фитнес-целей',
        login_features_workouts: 'Тренировки',
        login_features_nutrition: 'Питание',
        login_features_progress: 'Прогресс',

        // Register
        reg_title:          'Создать аккаунт',
        reg_subtitle:       'Начни путь к лучшей форме',
        reg_step_account:   'Аккаунт',
        reg_step_profile:   'Профиль',
        reg_name:           'Имя',
        reg_email:          'Email',
        reg_password:       'Пароль',
        reg_confirm:        'Подтвердите пароль',
        reg_gender:         'Пол',
        reg_male:           'Мужской',
        reg_female:         'Женский',
        reg_age:            'Возраст (лет)',
        reg_weight:         'Вес (кг)',
        reg_height:         'Рост (см)',
        reg_next:           'Далее',
        reg_back:           'Назад',
        reg_submit:         'Зарегистрироваться',
        reg_loading:        'Регистрация...',
        reg_has_account:    'Уже есть аккаунт?',
        reg_signin:         'Войти',

        // Home
        home_greeting:      'Привет,',
        home_user_fallback: 'Пользователь',
        home_goal_label:    'Цель:',
        home_kcal:          'ккал',
        home_motivation_next: 'Следующая \u2192',
        home_quick_add_workout:      'Добавить тренировку',
        home_quick_add_nutrition:    'Записать питание',
        home_quick_view_analytics:   'Посмотреть аналитику',
        home_quick_desc_workout:     'Зафиксируй активность',
        home_quick_desc_nutrition:   'Внеси прием пищи',
        home_quick_desc_analytics:   'Посмотри прогресс',
        home_recommendations:        'Рекомендации',

        // Motivational quotes
        quote_0: 'Каждая тренировка \u2014 это шаг ближе к лучшей версии себя.',
        quote_0a: 'Аноним',
        quote_1: 'Боль, которую ты чувствуешь сегодня, \u2014 это сила, которую ты почувствуешь завтра.',
        quote_1a: 'Аноним',
        quote_2: 'Не считай дни \u2014 делай дни счастливыми.',
        quote_2a: 'Мухаммед Али',
        quote_3: 'Успех \u2014 это сумма маленьких усилий, повторяемых день за днем.',
        quote_3a: 'Роберт Коллиер',
        quote_4: 'Тело способно на большее. Убеди в этом свой разум.',
        quote_4a: 'Аноним',
        quote_5: 'Тяжело в тренировке \u2014 легко в бою.',
        quote_5a: 'А. В. Суворов',
        quote_6: 'Хочешь изменить тело \u2014 начни с мысли.',
        quote_6a: 'Аноним',
        quote_7: 'Единственная плохая тренировка \u2014 та, которую ты пропустил.',
        quote_7a: 'Аноним',

        // Footer
        footer_rights:   'Все права защищены.',
        footer_about:    'О проекте',
        footer_about_body:
            'Данная работа выполнена студентом Казанского Федерального Университета, ' +
            'направление Прикладная информатика, группа 09-253, ' +
            'Богдановым Артуром Владимировичем.',
        footer_close:    'Закрыть',

        // Common
        loading:         'Загрузка...',
        save:            'Сохранить',
        cancel:          'Отмена',
        delete_:         'Удалить',
        edit_:           'Редактировать',
        add_:            'Добавить',
        close_:          'Закрыть',
        search_:         'Поиск...',
        no_data:         'Нет данных',

        // Analytics
        analytics_title:      'Аналитика',
        analytics_subtitle:   'Анализируй свой прогресс и достижения',
        analytics_export_csv: 'Экспорт CSV',
        analytics_7days:      '7 дней',
        analytics_30days:     '30 дней',
        analytics_year:       'Год',
        analytics_workouts:   'Тренировок',
        analytics_burned:     'Сожжено',
        analytics_time:       'Время',
        analytics_consumed:   'Съедено',
        analytics_unit_pcs:   'шт',
        analytics_unit_kcal:  'ккал',
        analytics_unit_min:   'мин',
        analytics_per_workout: 'за тренировку',
        analytics_per_day:    'ккал/день',
        analytics_no_data:    'нет данных',
        analytics_for_days:   'за',
        analytics_days:       'дней',
        analytics_cal_burned_chart: 'Сожжённые калории (тренировки)',
        analytics_workout_types: 'Типы тренировок',
        analytics_duration_chart: 'Длительность тренировок (мин)',
        analytics_nutrition_chart: 'Калории из питания',
        analytics_recent_workouts: 'Последние тренировки',
        analytics_no_data_period: 'Нет данных за выбранный период',
        analytics_no_data_hint: 'Добавьте тренировки в календарь, чтобы увидеть статистику',
        analytics_no_nutrition: 'Нет данных о питании',
        analytics_workout_fallback: 'Тренировка',
        analytics_csv_workouts_header: '=== ТРЕНИРОВКИ ===',
        analytics_csv_date: 'Дата',
        analytics_csv_type: 'Тип',
        analytics_csv_duration: 'Длительность (мин)',
        analytics_csv_cal_burned: 'Калорий сожжено',
        analytics_csv_note: 'Примечание',
        analytics_csv_nutrition_header: '=== ПИТАНИЕ ===',
        analytics_csv_calories: 'Калории',
        analytics_csv_protein: 'Белки (г)',
        analytics_csv_fat: 'Жиры (г)',
        analytics_csv_carbs: 'Углеводы (г)',

        // Profile
        profile_tab_profile:  'Профиль',
        profile_tab_weight:   'Динамика веса',
        profile_tab_goals:    'Цели',
        profile_tab_workouts: 'Тренировки',
        profile_personal_data: 'Личные данные',
        profile_edit_btn:     'Редактировать',
        profile_name:         'Имя',
        profile_email:        'Email',
        profile_gender:       'Пол',
        profile_gender_male:  'Мужской',
        profile_gender_male_icon: '👨 Мужской',
        profile_gender_female: 'Женский',
        profile_gender_female_icon: '👩 Женский',
        profile_age:          'Возраст',
        profile_weight:       'Вес',
        profile_height:       'Рост',
        profile_activity:     'Активность',
        profile_activity_level: 'Уровень активности',
        profile_sedentary:    'Сидячий',
        profile_light:        'Лёгкая',
        profile_moderate:     'Умеренная',
        profile_active:       'Высокая',
        profile_veryActive:   'Очень высокая',
        profile_sedentary_full: '🪑 Сидячий образ жизни',
        profile_light_full:   '🚶 Лёгкая активность (1–2 раза/нед)',
        profile_moderate_full: '🏃 Умеренная активность (3–5 раз/нед)',
        profile_active_full:  '💪 Высокая активность (6–7 раз/нед)',
        profile_veryActive_full: '🔥 Очень высокая (спорт + физ. работа)',
        profile_years:        'лет',
        profile_kg:           'кг',
        profile_cm:           'см',
        profile_workouts_count: 'Тренировок',
        profile_minutes:      'Минут',
        profile_kcal_burned:  'Ккал сожжено',
        profile_goals_done:   'Целей выполнено',
        profile_weight_chart: 'Динамика веса',
        profile_no_weight:    'Нет данных о весе',
        profile_no_weight_hint: 'Обновите профиль с весом, чтобы увидеть историю',
        profile_goals_empty:  'Целей пока нет',
        profile_goals_hint:   'Добавьте цель в календаре',
        profile_deadline:     'Дедлайн:',
        profile_completed:    '✅ Выполнено',
        profile_delete_goal:  'Удалить цель',
        profile_workouts_empty: 'Нет тренировок',
        profile_save:         'Сохранить',
        profile_saving:       'Сохранение...',
        profile_cancel:       'Отмена',
        profile_updated:      'Профиль обновлён!',

        // Nutrition
        nutr_title:           'Дневник питания',
        nutr_subtitle:        'Отслеживай калории и макронутриенты',
        nutr_add_btn:         '+ Добавить',
        nutr_cancel_btn:      '✕ Отмена',
        nutr_today:           'Сегодня',
        nutr_add_meal_title:  'Добавить приём пищи',
        nutr_search_label:    'Поиск продукта в базе',
        nutr_search_placeholder: 'Начните вводить название (например: курица, рис...)',
        nutr_searching:       'Поиск...',
        nutr_dish_label:      'Название блюда / продукта *',
        nutr_dish_placeholder: 'Например: Гречка с курицей',
        nutr_meal_type:       'Приём пищи',
        nutr_portion:         'Порция, г',
        nutr_calories_label:  'Калории *',
        nutr_protein:         'Белки, г',
        nutr_fat:             'Жиры, г',
        nutr_carbs:           'Углеводы, г',
        nutr_save:            'Сохранить',
        nutr_saving:          'Сохранение...',
        nutr_cancel:          'Отмена',
        nutr_total_calories:  'Калории',
        nutr_total_protein:   'Белки',
        nutr_total_fat:       'Жиры',
        nutr_total_carbs:     'Углеводы',
        nutr_no_entries:      'Нет записей питания',
        nutr_no_entries_hint: 'Нажмите «+ Добавить», чтобы записать приём пищи',
        nutr_delete_entry:    'Удалить запись',
        nutr_kcal:            'ккал',
        nutr_per100g:         'ккал / 100г',
        nutr_added:           'Запись добавлена!',
        nutr_deleted:         'Запись удалена',
        nutr_err_fields:      'Укажите название и калории',
        nutr_err_add:         'Ошибка при добавлении',
        nutr_err_delete:      'Ошибка при удалении',
        nutr_meal_breakfast:  'Завтрак',
        nutr_meal_lunch:      'Обед',
        nutr_meal_dinner:     'Ужин',
        nutr_meal_snack:      'Перекус',

        // DailyStats
        daily_consumed:       'Потреблено',
        daily_burned:         'Сожжено',
        daily_balance:        'Баланс',
        daily_recommended:    'Рекоменд.',
        daily_kcal:           'ккал',

        // CalorieCalculator
        calc_title:           'Калькулятор калорий',
        calc_activity:        'Активность',
        calc_goal:            'Цель',
        calc_lose:            'Похудение',
        calc_maintain:        'Поддержание',
        calc_gain:            'Набор массы',
        calc_result_label:    'Суточная норма',
        calc_protein:         'Белки (30%)',
        calc_fat:             'Жиры (30%)',
        calc_carbs:           'Углеводы (40%)',
        calc_kcal_day:        'ккал / день',

        // WorkoutRecommendations
        wrec_title:           'Рекомендации по тренировкам',
        wrec_level_beginner:  '🟢 Начинающий',
        wrec_level_intermediate: '🟡 Средний уровень',
        wrec_level_advanced:  '🔴 Продвинутый',
        wrec_types_label:     'Типы тренировок',
        wrec_unavailable:     'Рекомендации временно недоступны',
        wrec_sets:            'сет.',
        wrec_reps:            'повт.',

        // Calendar
        cal_add_workout:      'Добавить тренировку',
        cal_add_goal:         'Добавить цель',
        cal_workout_type:     'Вид тренировки',
        cal_workout_duration: 'Длительность (мин)',
        cal_calories_burned:  'Калорий сожжено',
        cal_workout_time:     'Время тренировки',
        cal_comment:          'Комментарий (необязательно)',
        cal_goal_name:        'Название цели',
        cal_goal_deadline:    'Дедлайн',
        cal_save:             'Сохранить',
        cal_saving:           'Сохранение...',
        cal_cancel:           'Отмена',
        cal_delete:           'Удалить',
        cal_no_events:        'Нет событий',
        cal_workouts_title:   'Тренировки',
        cal_goals_title:      'Цели',
        cal_workout_added:    'Тренировка добавлена!',
        cal_goal_added:       'Цель добавлена!',
        cal_deleted:          'Удалено',
        cal_error:            'Ошибка при сохранении',
    },

    en: {
        // Header / Nav
        nav_home:       'Home',
        nav_nutrition:  'Nutrition',
        nav_analytics:  'Analytics',
        nav_profile:    'Profile',
        nav_login:      'Log in',
        nav_register:   'Sign up',
        nav_logout:     'Log out',
        toggle_theme:   'Toggle theme',
        toggle_lang:    'RU',

        // Login
        login_title:        'Welcome back',
        login_subtitle:     'Sign in to your account to continue',
        login_email:        'Email',
        login_password:     'Password',
        login_show_pass:    'Show password',
        login_hide_pass:    'Hide password',
        login_forgot:       'Forgot password?',
        login_submit:       'Sign in',
        login_loading:      'Signing in...',
        login_no_account:   'No account?',
        login_signup:       'Sign up',
        login_slogan:       'Your personal assistant for achieving fitness goals',
        login_features_workouts: 'Workouts',
        login_features_nutrition: 'Nutrition',
        login_features_progress: 'Progress',

        // Register
        reg_title:          'Create account',
        reg_subtitle:       'Start your journey to a better shape',
        reg_step_account:   'Account',
        reg_step_profile:   'Profile',
        reg_name:           'Name',
        reg_email:          'Email',
        reg_password:       'Password',
        reg_confirm:        'Confirm password',
        reg_gender:         'Gender',
        reg_male:           'Male',
        reg_female:         'Female',
        reg_age:            'Age (years)',
        reg_weight:         'Weight (kg)',
        reg_height:         'Height (cm)',
        reg_next:           'Next',
        reg_back:           'Back',
        reg_submit:         'Create account',
        reg_loading:        'Creating account...',
        reg_has_account:    'Already have an account?',
        reg_signin:         'Sign in',

        // Home
        home_greeting:      'Hello,',
        home_user_fallback: 'User',
        home_goal_label:    'Goal:',
        home_kcal:          'kcal',
        home_motivation_next: 'Next \u2192',
        home_quick_add_workout:      'Add workout',
        home_quick_add_nutrition:    'Log nutrition',
        home_quick_view_analytics:   'View analytics',
        home_quick_desc_workout:     'Record your activity',
        home_quick_desc_nutrition:   'Log your meal',
        home_quick_desc_analytics:   'Check your progress',
        home_recommendations:        'Recommendations',

        // Motivational quotes
        quote_0: 'Every workout is a step closer to the best version of yourself.',
        quote_0a: 'Anonymous',
        quote_1: "The pain you feel today is the strength you'll feel tomorrow.",
        quote_1a: 'Anonymous',
        quote_2: "Don't count the days \u2014 make the days count.",
        quote_2a: 'Muhammad Ali',
        quote_3: 'Success is the sum of small efforts repeated day after day.',
        quote_3a: 'Robert Collier',
        quote_4: 'Your body can do it. It is your mind you need to convince.',
        quote_4a: 'Anonymous',
        quote_5: 'Train hard, fight easy.',
        quote_5a: 'A. V. Suvorov',
        quote_6: 'Want to change your body \u2014 start with your mind.',
        quote_6a: 'Anonymous',
        quote_7: 'The only bad workout is the one that did not happen.',
        quote_7a: 'Anonymous',

        // Footer
        footer_rights:   'All rights reserved.',
        footer_about:    'About',
        footer_about_body:
            'This project was developed by a student of Kazan Federal University, ' +
            'Applied Informatics program, group 09-253, ' +
            'Artur Bogdanov.',
        footer_close:    'Close',

        // Common
        loading:         'Loading...',
        save:            'Save',
        cancel:          'Cancel',
        delete_:         'Delete',
        edit_:           'Edit',
        add_:            'Add',
        close_:          'Close',
        search_:         'Search...',
        no_data:         'No data',

        // Analytics
        analytics_title:      'Analytics',
        analytics_subtitle:   'Track your progress and achievements',
        analytics_export_csv: 'Export CSV',
        analytics_7days:      '7 days',
        analytics_30days:     '30 days',
        analytics_year:       'Year',
        analytics_workouts:   'Workouts',
        analytics_burned:     'Burned',
        analytics_time:       'Time',
        analytics_consumed:   'Consumed',
        analytics_unit_pcs:   'pcs',
        analytics_unit_kcal:  'kcal',
        analytics_unit_min:   'min',
        analytics_per_workout: 'per workout',
        analytics_per_day:    'kcal/day',
        analytics_no_data:    'no data',
        analytics_for_days:   'for',
        analytics_days:       'days',
        analytics_cal_burned_chart: 'Calories burned (workouts)',
        analytics_workout_types: 'Workout types',
        analytics_duration_chart: 'Workout duration (min)',
        analytics_nutrition_chart: 'Calories from nutrition',
        analytics_recent_workouts: 'Recent workouts',
        analytics_no_data_period: 'No data for selected period',
        analytics_no_data_hint: 'Add workouts to the calendar to see statistics',
        analytics_no_nutrition: 'No nutrition data',
        analytics_workout_fallback: 'Workout',
        analytics_csv_workouts_header: '=== WORKOUTS ===',
        analytics_csv_date: 'Date',
        analytics_csv_type: 'Type',
        analytics_csv_duration: 'Duration (min)',
        analytics_csv_cal_burned: 'Calories burned',
        analytics_csv_note: 'Note',
        analytics_csv_nutrition_header: '=== NUTRITION ===',
        analytics_csv_calories: 'Calories',
        analytics_csv_protein: 'Protein (g)',
        analytics_csv_fat: 'Fat (g)',
        analytics_csv_carbs: 'Carbs (g)',

        // Profile
        profile_tab_profile:  'Profile',
        profile_tab_weight:   'Weight history',
        profile_tab_goals:    'Goals',
        profile_tab_workouts: 'Workouts',
        profile_personal_data: 'Personal data',
        profile_edit_btn:     'Edit',
        profile_name:         'Name',
        profile_email:        'Email',
        profile_gender:       'Gender',
        profile_gender_male:  'Male',
        profile_gender_male_icon: '👨 Male',
        profile_gender_female: 'Female',
        profile_gender_female_icon: '👩 Female',
        profile_age:          'Age',
        profile_weight:       'Weight',
        profile_height:       'Height',
        profile_activity:     'Activity',
        profile_activity_level: 'Activity level',
        profile_sedentary:    'Sedentary',
        profile_light:        'Light',
        profile_moderate:     'Moderate',
        profile_active:       'Active',
        profile_veryActive:   'Very active',
        profile_sedentary_full: '🪑 Sedentary lifestyle',
        profile_light_full:   '🚶 Light activity (1–2 times/week)',
        profile_moderate_full: '🏃 Moderate activity (3–5 times/week)',
        profile_active_full:  '💪 High activity (6–7 times/week)',
        profile_veryActive_full: '🔥 Very high (sport + physical work)',
        profile_years:        'years',
        profile_kg:           'kg',
        profile_cm:           'cm',
        profile_workouts_count: 'Workouts',
        profile_minutes:      'Minutes',
        profile_kcal_burned:  'Kcal burned',
        profile_goals_done:   'Goals done',
        profile_weight_chart: 'Weight history',
        profile_no_weight:    'No weight data',
        profile_no_weight_hint: 'Update your profile with weight to see history',
        profile_goals_empty:  'No goals yet',
        profile_goals_hint:   'Add a goal in the calendar',
        profile_deadline:     'Deadline:',
        profile_completed:    '✅ Completed',
        profile_delete_goal:  'Delete goal',
        profile_workouts_empty: 'No workouts',
        profile_save:         'Save',
        profile_saving:       'Saving...',
        profile_cancel:       'Cancel',
        profile_updated:      'Profile updated!',

        // Nutrition
        nutr_title:           'Nutrition diary',
        nutr_subtitle:        'Track calories and macronutrients',
        nutr_add_btn:         '+ Add',
        nutr_cancel_btn:      '✕ Cancel',
        nutr_today:           'Today',
        nutr_add_meal_title:  'Add meal',
        nutr_search_label:    'Search food in database',
        nutr_search_placeholder: 'Start typing a name (e.g. chicken, rice...)',
        nutr_searching:       'Searching...',
        nutr_dish_label:      'Dish / product name *',
        nutr_dish_placeholder: 'E.g. Buckwheat with chicken',
        nutr_meal_type:       'Meal type',
        nutr_portion:         'Portion, g',
        nutr_calories_label:  'Calories *',
        nutr_protein:         'Protein, g',
        nutr_fat:             'Fat, g',
        nutr_carbs:           'Carbs, g',
        nutr_save:            'Save',
        nutr_saving:          'Saving...',
        nutr_cancel:          'Cancel',
        nutr_total_calories:  'Calories',
        nutr_total_protein:   'Protein',
        nutr_total_fat:       'Fat',
        nutr_total_carbs:     'Carbs',
        nutr_no_entries:      'No nutrition entries',
        nutr_no_entries_hint: 'Click "+ Add" to log a meal',
        nutr_delete_entry:    'Delete entry',
        nutr_kcal:            'kcal',
        nutr_per100g:         'kcal / 100g',
        nutr_added:           'Entry added!',
        nutr_deleted:         'Entry deleted',
        nutr_err_fields:      'Please fill in name and calories',
        nutr_err_add:         'Error adding entry',
        nutr_err_delete:      'Error deleting entry',
        nutr_meal_breakfast:  'Breakfast',
        nutr_meal_lunch:      'Lunch',
        nutr_meal_dinner:     'Dinner',
        nutr_meal_snack:      'Snack',

        // DailyStats
        daily_consumed:       'Consumed',
        daily_burned:         'Burned',
        daily_balance:        'Balance',
        daily_recommended:    'Goal',
        daily_kcal:           'kcal',

        // CalorieCalculator
        calc_title:           'Calorie calculator',
        calc_activity:        'Activity',
        calc_goal:            'Goal',
        calc_lose:            'Weight loss',
        calc_maintain:        'Maintenance',
        calc_gain:            'Muscle gain',
        calc_result_label:    'Daily target',
        calc_protein:         'Protein (30%)',
        calc_fat:             'Fat (30%)',
        calc_carbs:           'Carbs (40%)',
        calc_kcal_day:        'kcal / day',

        // WorkoutRecommendations
        wrec_title:           'Workout recommendations',
        wrec_level_beginner:  '🟢 Beginner',
        wrec_level_intermediate: '🟡 Intermediate',
        wrec_level_advanced:  '🔴 Advanced',
        wrec_types_label:     'Workout types',
        wrec_unavailable:     'Recommendations temporarily unavailable',
        wrec_sets:            'sets',
        wrec_reps:            'reps',

        // Calendar
        cal_add_workout:      'Add workout',
        cal_add_goal:         'Add goal',
        cal_workout_type:     'Workout type',
        cal_workout_duration: 'Duration (min)',
        cal_calories_burned:  'Calories burned',
        cal_workout_time:     'Workout time',
        cal_comment:          'Comment (optional)',
        cal_goal_name:        'Goal name',
        cal_goal_deadline:    'Deadline',
        cal_save:             'Save',
        cal_saving:           'Saving...',
        cal_cancel:           'Cancel',
        cal_delete:           'Delete',
        cal_no_events:        'No events',
        cal_workouts_title:   'Workouts',
        cal_goals_title:      'Goals',
        cal_workout_added:    'Workout added!',
        cal_goal_added:       'Goal added!',
        cal_deleted:          'Deleted',
        cal_error:            'Error saving',
    },
};

// ─── Hook ─────────────────────────────────────────────────────────────────────
export const useLang = () => useContext(LanguageContext);

// ─── Provider ─────────────────────────────────────────────────────────────────
export const LanguageProvider = ({ children }) => {
    const [lang, setLang] = useState(() => {
        return localStorage.getItem('lang') || 'ru';
    });

    const toggleLang = () => {
        const next = lang === 'ru' ? 'en' : 'ru';
        setLang(next);
        localStorage.setItem('lang', next);
    };

    // t(key) — returns translation for the current language
    const t = (key) => translations[lang]?.[key] ?? translations['ru']?.[key] ?? key;

    return (
        <LanguageContext.Provider value={{ lang, setLang, toggleLang, t }}>
            {children}
        </LanguageContext.Provider>
    );
};
